-- Development seed data — run manually with:
--   pnpm supabase db seed
-- DO NOT include in the numbered migrations sequence.
-- ref_code is generated by next_practitioner_ref() to stay consistent with prod sequence.

INSERT INTO practitioners (name, email, role, org, city, state, experience, modules, status, ref_code) VALUES
  ('Priya Sharma',    'priya.sharma@gmail.com',   'Certified Financial Planner',  'Independent CFP Practice', 'Hyderabad', 'Telangana',     '9 – 12 years',  ARRAY['Foundations of Personal Finance', 'Retirement & Goal-Based Financial Planning'], 'Empanelled',     next_practitioner_ref()),
  ('Vikram Kulkarni', 'vikram.k@gmail.com',        'Equity Analyst',               'Motilal Oswal',            'Mumbai',    'Maharashtra',   '9 – 12 years',  ARRAY['Equity Investing Simplified'],                                                    'Agreement Sent', next_practitioner_ref()),
  ('Anita Menon',     'anita.menon@gmail.com',     'Portfolio Manager',            'HDFC AMC',                 'Bengaluru', 'Karnataka',     '13 – 18 years', ARRAY['Asset Allocation & Portfolio Construction', 'Investment Solutions & Portfolio Strategies'], 'Screening Done', next_practitioner_ref()),
  ('Rohan Desai',     'rohan.desai@gmail.com',     'Wealth Advisor',               'IIFL Wealth',              'Pune',      'Maharashtra',   '5 – 8 years',   ARRAY['Retirement & Goal-Based Financial Planning'],                                     'Under Review',   next_practitioner_ref()),
  ('Sneha Nair',      'sneha.nair@gmail.com',      'CFP & Retirement Specialist',  'Independent Practice',     'Chennai',   'Tamil Nadu',    '9 – 12 years',  ARRAY['Retirement & Goal-Based Financial Planning', 'Debt & Fixed Income Investing'],    'Applied',        next_practitioner_ref()),
  ('Karan Mehta',     'karan.mehta@gmail.com',     'Relationship Manager',         'Axis Bank Wealth',         'Delhi',     'Delhi',         '5 – 8 years',   ARRAY['Foundations of Personal Finance'],                                                'Rejected',       next_practitioner_ref())
ON CONFLICT (email) DO NOTHING;
