-- Development seed data — run manually with:
--   pnpm supabase db seed
-- DO NOT include in the numbered migrations sequence.
-- ref_code is generated by next_practitioner_ref() to stay consistent with prod sequence.

INSERT INTO practitioners (name, email, role, org, city, experience, modules, status, ref_code) VALUES
  ('Priya Sharma',    'priya.sharma@gmail.com',  'Certified Financial Planner', 'Independent CFP Practice', 'Hyderabad', '9 – 12 years',  ARRAY['Financial Planning Basics'], 'Empanelled',     next_practitioner_ref()),
  ('Vikram Kulkarni', 'vikram.k@gmail.com',       'Equity Analyst',             'Motilal Oswal',            'Mumbai',    '9 – 12 years',  ARRAY['Stock Market Basics'],        'Agreement Sent', next_practitioner_ref()),
  ('Anita Menon',     'anita.menon@gmail.com',    'Portfolio Manager',          'HDFC AMC',                 'Bengaluru', '13 – 18 years', ARRAY['Market Fundamentals'],         'Screening Done', next_practitioner_ref()),
  ('Rohan Desai',     'rohan.desai@gmail.com',    'Wealth Advisor',             'IIFL Wealth',              'Pune',      '5 – 8 years',   ARRAY['Goal-Based Investing'],        'Under Review',   next_practitioner_ref()),
  ('Sneha Nair',      'sneha.nair@gmail.com',     'CFP & Retirement Specialist','Independent Practice',     'Chennai',   '9 – 12 years',  ARRAY['Retirement Planning'],         'Applied',        next_practitioner_ref()),
  ('Karan Mehta',     'karan.mehta@gmail.com',    'Relationship Manager',       'Axis Bank Wealth',         'Delhi',     '5 – 8 years',   ARRAY['Investment Basics'],           'Rejected',       next_practitioner_ref())
ON CONFLICT (email) DO NOTHING;
