// GENERATED by scripts/build-legal-content.mjs — do not edit.
//
// Source: docs/legal/privacy-policy.md, docs/legal/terms-of-use.md, converted from the client's
// .docx originals. Change the wording there and re-run the script.

export type LegalBlock =
  | { type: "heading"; level: number; text: string }
  | { type: "paragraph"; text: string }
  | { type: "list"; items: string[] };

export interface LegalDocument {
  key: "privacy" | "terms";
  title: string;
  blocks: LegalBlock[];
}

export const LEGAL_DOCUMENTS: readonly LegalDocument[] = [
  {
    "key": "privacy",
    "title": "Privacy Policy",
    "blocks": [
      {
        "type": "paragraph",
        "text": "By accessing our website (www.iqcommune.com), you consent to a legally binding agreement with InvestQ Commune, which owns and administers this website and the iqcommune platform. InvestQ Commune connects independent finance professionals (“Practitioners”) with organisations and individuals seeking in-person financial literacy sessions (“Requestors”), and during this may become privy to personal information of Practitioners, Requestors, and other visitors to the Website."
      },
      {
        "type": "paragraph",
        "text": "For the purpose of this Privacy Policy, wherever the context so requires, the term “You” or “User” shall mean any natural or legal person accessing this Website, including Practitioners, Requestors, and other visitors, and the term “We”, “Us”, “Our” shall mean InvestQ Commune."
      },
      {
        "type": "paragraph",
        "text": "We at InvestQ Commune respect the privacy of everyone who visits this website and are committed to maintaining the privacy and security of the personal information of all visitors to this Website."
      },
      {
        "type": "paragraph",
        "text": "We view the protection of your privacy as a very important principle. We store and process your information on systems that are protected by physical as well as reasonable technological security measures and procedures. If you object to your information being used in this way, please do not provide your details on the Website."
      },
      {
        "type": "paragraph",
        "text": "InvestQ Commune does not sell, rent, or trade your personal information or contact details to any third party. We may share information strictly as needed to coordinate and deliver sessions — for example, sharing a Practitioner’s brief professional profile with a confirmed Requestor, as contemplated under the Practitioner’s empanelment agreement — or as required by law."
      },
      {
        "type": "paragraph",
        "text": "Our policy on the collection and use of personal information is outlined below."
      },
      {
        "type": "heading",
        "level": 1,
        "text": "Collection of Personal Information"
      },
      {
        "type": "paragraph",
        "text": "InvestQ Commune collects personal information for the purpose of correspondence, coordinating sessions, and administering its relationship with Practitioners and Requestors. This includes:"
      },
      {
        "type": "heading",
        "level": 2,
        "text": "For Practitioners (collected at the time of application, and in line with the Empanelment Agreement they sign):"
      },
      {
        "type": "list",
        "items": [
          "Name, professional role/designation, current employer or organisation, city and state, email address, and phone number;",
          "Years of experience and area(s) of expertise / preferred module(s);",
          "Communication or correspondence address, and details such as T-shirt size, for session-related purposes;",
          "Bank account or UPI details, collected solely for the purpose of processing revenue-share payouts."
        ]
      },
      {
        "type": "heading",
        "level": 2,
        "text": "For Requestors / points of contact for a session (collected at the time of a session request):"
      },
      {
        "type": "list",
        "items": [
          "Name, email address, phone number, and organisation name;",
          "Session requirements such as topic, city, group size, and preferred dates, and venue details."
        ]
      },
      {
        "type": "paragraph",
        "text": "InvestQ Commune does not collect Aadhaar, PAN, GST, or other identity or tax documents through the Platform. Any invoicing, tax, or payment-related documentation required from a Practitioner is handled separately and directly with InvestQ Commune’s finance team, off-platform, and is not collected or stored through the Website."
      },
      {
        "type": "paragraph",
        "text": "The information collected shall be used only for the purpose for which it has been collected — principally, correspondence, and coordinating and confirming sessions and related logistics."
      },
      {
        "type": "paragraph",
        "text": "By using the services offered by InvestQ Commune, you agree to the collection and use of your personal information as described in this Privacy Policy."
      },
      {
        "type": "heading",
        "level": 1,
        "text": "Right to Opt-Out"
      },
      {
        "type": "paragraph",
        "text": "You always have the right to refuse or withdraw your consent to the use of your personal information by writing to us at hello@iqcommune.com. However, in such an event, we may not be able to continue coordinating sessions or correspondence with you. An opt-out request will not apply to correspondence already initiated."
      },
      {
        "type": "heading",
        "level": 1,
        "text": "Communications"
      },
      {
        "type": "paragraph",
        "text": "When you use the Website or send emails or other data, information, or communication to us, you agree and understand that you are communicating with us through electronic records, and you consent to receive communications via electronic records from us periodically and as and when required. We may communicate with you by email or by other mode of communication, electronic or otherwise."
      },
      {
        "type": "heading",
        "level": 1,
        "text": "Log File Information Collected and Stored Automatically (Cookies)"
      },
      {
        "type": "paragraph",
        "text": "When you visit our site, our servers automatically record certain information that your web browser sends whenever you visit our website. The kind of information gathered automatically includes the type of browser and operating system you are using, the domain name of your Internet Service Provider, the date and time of your visit, and the pages on our website. We sometimes use this information to improve our website’s design and content, and primarily to give you a better browsing experience."
      },
      {
        "type": "paragraph",
        "text": "This notice/policy is not intended to and does not create any contractual or other legal rights in favour of any user or viewer of this website or on behalf of any other party. However, users and viewers are informed that by using the website, they are deemed to have consented to the collection and use of information by InvestQ Commune as stated above."
      },
      {
        "type": "paragraph",
        "text": "If you’d prefer to restrict, block, or delete cookies from this website, or any other website, you can use your browser to do this. Each browser is different, so check the ‘Help’ menu of your browser to learn how to change your cookie preferences. If you choose to disable all cookies, we cannot guarantee the performance of our website, and some features may not work as expected."
      },
      {
        "type": "heading",
        "level": 1,
        "text": "Updating or Reviewing Your Personal Information"
      },
      {
        "type": "paragraph",
        "text": "You may, upon written request to hello@iqcommune.com, review the personal information you have provided to us. InvestQ Commune shall ensure that any personal information found to be inaccurate or deficient is corrected or amended as feasible."
      },
      {
        "type": "heading",
        "level": 1,
        "text": "Reasonable Security Practices for Protecting Information"
      },
      {
        "type": "paragraph",
        "text": "InvestQ Commune uses commercially reasonable physical, managerial, and technical safeguards to preserve the integrity and security of your personal information. InvestQ Commune cannot, however, ensure or warrant the security of any information you transmit to us, and you do so at your own risk. Once we receive your information, InvestQ Commune makes commercially reasonable efforts to ensure the security of our systems. Please note that this is not a guarantee that such information may not be accessed, disclosed, altered, or destroyed by breach of any of our physical, technical, or managerial safeguards."
      },
      {
        "type": "heading",
        "level": 1,
        "text": "Links to Other Websites"
      },
      {
        "type": "paragraph",
        "text": "Our website sometimes has links to other website(s) on the World Wide Web. The privacy policies of these website(s) are not under our control. Once you leave our servers, use of any information you provide is governed by the privacy policy of the operator of the site you are visiting. It is advisable to read their privacy policies for further information."
      },
      {
        "type": "heading",
        "level": 1,
        "text": "Notification Procedures"
      },
      {
        "type": "paragraph",
        "text": "InvestQ Commune provides notifications, whether such notifications are required by law or are for marketing or other business-related purposes, to you via email notice, written or hard copy notice, or through conspicuous posting of such notice on our website, as determined by InvestQ Commune in its sole discretion. InvestQ Commune reserves the right to determine the form and means of providing notifications to you, provided that you may opt out of certain means of notification as described in this Privacy Policy."
      },
      {
        "type": "heading",
        "level": 1,
        "text": "Changes to Our Privacy Policy"
      },
      {
        "type": "paragraph",
        "text": "Please note that this policy may change from time to time. If InvestQ Commune changes its privacy policies and procedures, InvestQ Commune will post those changes on www.iqcommune.com to keep you aware of what information we collect, how we use it, and under what circumstances we may disclose it. Changes to this Privacy Policy are effective when they are posted on this page. Please visit our website to keep yourself abreast of any changes to this policy."
      },
      {
        "type": "heading",
        "level": 1,
        "text": "Contact"
      },
      {
        "type": "paragraph",
        "text": "For any questions about this Privacy Policy, or to exercise any of the rights described above, please write to us at hello@iqcommune.com."
      }
    ]
  },
  {
    "key": "terms",
    "title": "Terms of Use",
    "blocks": [
      {
        "type": "paragraph",
        "text": "This section contains the Terms of Use of www.iqcommune.com (the “Website” or “Platform”). By accessing our website, you consent to a legally binding agreement with InvestQ Commune, which owns and administers this Website and the iqcommune platform. By using and/or accessing our website and any of its pages, you agree to read, understand, and agree to all the terms and conditions set out below."
      },
      {
        "type": "heading",
        "level": 1,
        "text": "Nature of the Platform and Sessions"
      },
      {
        "type": "paragraph",
        "text": "iqcommune is a platform operated by InvestQ Commune that connects independent, experienced finance professionals (“Practitioners”) with organisations, groups, and individuals (“Requestors”) seeking in-person financial literacy sessions. InvestQ Commune facilitates the introduction, scheduling, and coordination of these sessions. InvestQ Commune is not itself a financial advisor, broker, or provider of investment products or services, and does not render financial or investment advice through the Platform."
      },
      {
        "type": "paragraph",
        "text": "Sessions delivered through the Platform are strictly educational in nature. As a condition of empanelment with InvestQ Commune, Practitioners are required to focus only on explaining financial concepts, frameworks, and the underlying mechanisms of personal finance and investing, so as to improve the financial literacy of participants. Practitioners are expressly prohibited from promoting, recommending, or selling any specific financial product, scheme, fund, security, or policy — whether their own, their employer’s, or any third party’s — during a session. A Practitioner found to be in breach of this may be removed from the Platform."
      },
      {
        "type": "paragraph",
        "text": "Nothing said or presented during a session should be construed as personalised financial or investment advice. Participants should seek independent professional advice before making any financial decision."
      },
      {
        "type": "heading",
        "level": 1,
        "text": "Use of Information and Materials"
      },
      {
        "type": "paragraph",
        "text": "The information and materials on this Website are provided for general informational purposes relating to the services offered by InvestQ Commune. InvestQ Commune retains the absolute right to determine eligibility for participation in, or provision of, any of its services."
      },
      {
        "type": "paragraph",
        "text": "By agreeing to these Terms & Conditions, you authorise InvestQ Commune and its representatives and agents to contact you regarding your session request, application, or enquiry through any mode including telephone calls, SMS, email, or letters, and confirm that laws relating to unsolicited communication under the “National Do Not Call Registry” as laid down by the Telecom Regulatory Authority of India will not apply to such communication."
      },
      {
        "type": "paragraph",
        "text": "The information contained in these pages is not intended to provide professional advice. Persons accessing these pages should obtain appropriate professional advice when necessary."
      },
      {
        "type": "heading",
        "level": 1,
        "text": "Our Trademarks and Copyright"
      },
      {
        "type": "paragraph",
        "text": "The content and information contained within our website or delivered to you in connection with your use of our website, is the property of InvestQ Commune and any other third party (where applicable). The trademarks, trade names, and logos (the “Trademarks”) used and displayed on our website include registered and unregistered Trademarks of InvestQ Commune and other third parties. Nothing on our website should be construed as granting any license or right to use any Trademarks displayed on our website. InvestQ Commune retains all proprietary rights on its website. Users are prohibited from using the same without the written permission of InvestQ Commune or such other parties, as applicable. The materials on this website are protected by copyright, and no part of such materials may be modified, reproduced, stored in a retrieval system, transmitted (in any form or by any means), copied, distributed, used for creating derivative works, or used in any other way for commercial or public purposes without the prior written consent of InvestQ Commune."
      },
      {
        "type": "heading",
        "level": 1,
        "text": "No Warranties"
      },
      {
        "type": "paragraph",
        "text": "Whilst every care has been taken in preparing the information and materials contained in this site, such information and materials are provided “as is” without warranty of any kind, either express or implied. In particular, no warranty regarding non-infringement, security, accuracy, fitness for a purpose, or freedom from computer viruses is given in connection with such information and materials."
      },
      {
        "type": "paragraph",
        "text": "InvestQ Commune facilitates the connection between Practitioners and Requestors. Practitioners are independent professionals and are not employees or agents of InvestQ Commune. InvestQ Commune is not responsible for the specific content, opinions, or views shared by a Practitioner during a session."
      },
      {
        "type": "heading",
        "level": 1,
        "text": "E-mail"
      },
      {
        "type": "paragraph",
        "text": "E-mail messages sent to InvestQ Commune over the Internet cannot be guaranteed to be completely secure. InvestQ Commune is not responsible for any damages incurred by users if they send a message to InvestQ Commune, or if InvestQ Commune sends a message to them at their request, over the Internet. InvestQ Commune is not responsible in any way for direct, indirect, special, or consequential damages arising out of the use of this Website."
      },
      {
        "type": "heading",
        "level": 1,
        "text": "Transmitting Over the Internet"
      },
      {
        "type": "paragraph",
        "text": "Due to the nature of the Internet, transactions may be subject to interruption, transmission blackout, delayed transmission, and incorrect data transmission. InvestQ Commune is not liable for malfunctions in communications facilities not under its control that may affect the accuracy or timeliness of messages and transactions you send."
      },
      {
        "type": "heading",
        "level": 1,
        "text": "Downloading"
      },
      {
        "type": "paragraph",
        "text": "We do not represent or warrant that the Site will be available and meet your requirements, that access will not be interrupted, that there will be no delays, failures, errors, or omissions or loss of transmitted information, that no viruses or other contaminating or destructive properties will be transmitted, or that no damage will occur to your computer system. You have sole responsibility for adequate protection and back-up of data and/or equipment, and for undertaking reasonable and appropriate precautions to scan for computer viruses or other destructive properties. We make no representations or warranties regarding the accuracy, functionality, or performance of any third-party software that may be used in connection with the Site."
      },
      {
        "type": "heading",
        "level": 1,
        "text": "Modification"
      },
      {
        "type": "paragraph",
        "text": "InvestQ Commune reserves the right to delete, modify, change, or discontinue any or all of the information on this website without giving notice to any user, individual, group of individuals, institutions, or any such governing bodies."
      },
      {
        "type": "heading",
        "level": 1,
        "text": "Governing Law"
      },
      {
        "type": "paragraph",
        "text": "The usage of this website and these Terms and Conditions shall be governed by and construed in accordance with the laws of India."
      },
      {
        "type": "heading",
        "level": 1,
        "text": "Jurisdiction"
      },
      {
        "type": "paragraph",
        "text": "Any dispute arising out of the usage of this website and the services provided by InvestQ Commune shall be subject to the exclusive jurisdiction of the Courts in Hyderabad, Telangana, India."
      },
      {
        "type": "heading",
        "level": 1,
        "text": "Internet Scanners and Intrusion Detection"
      },
      {
        "type": "paragraph",
        "text": "The system maintains a database of attack signatures which is continuously updated, and against which it scans incoming traffic to detect malicious activity or hacking attempts. In the event of a possible attack, the system will terminate that session, log the attack details, and alert the administrator."
      },
      {
        "type": "paragraph",
        "text": "IMPORTANT: By accessing this Website (www.iqcommune.com) and any of its pages, you are agreeing to the terms set out above."
      }
    ]
  }
] as const;
